export const categories = {
    Fiction: 'hardcover-fiction',
    NonFiction: 'hardcover-nonfiction',
    Business: 'business-books',
    Manga: 'manga',
    Animals:'animals',
    Crime: 'crime-and-punishment',
    Education: 'education',
    Espionage: 'espionage',
    Health: 'health',
    Humor: 'humor',
    Science: 'science',
    Political: 'hardcover-political-books',
    Family:'family',
    Relationships: 'relationships',
    Fashion: 'fashion-manners-and-customs',
    Children:'picture-books',
    Faith: 'religion-spirituality-and-faith',
    Sports: 'sports',
    Travel: 'travel',
    Celebrities:'Celebrities',
}